import { Tabs ,TabList, Tab, TabPanel,TabPanels} from '@chakra-ui/react'

export default function ManyTabs(){
  return (
    <>
      <Tabs  colorScheme="red" variant="line" >
      <TabList>
        <Tab>hoge</Tab>
        <Tab>huga</Tab>
        <Tab>hege</Tab>
      </TabList>
      <TabPanels>
        <TabPanel>
          <p>hogeone</p>
          <p>hogetwo</p>
          <p>hogethree</p>
        </TabPanel>
        <TabPanel>
          <p>hugaone</p>
          <p>hugatwo</p>
          <p>hugathree</p>
        </TabPanel>
        <TabPanel>
          <p>hegeone</p>
          <p>hegetwo</p>
          <p>hegethree</p>
        </TabPanel>
      </TabPanels>
      </Tabs>
      <Tabs  colorScheme="green" variant="enclosed" >
      <TabList>
        <Tab>hoge</Tab>
        <Tab>huga</Tab>
        <Tab>hege</Tab>
      </TabList>
      <TabPanels>
        <TabPanel>
          <p>hogeone</p>
          <p>hogetwo</p>
          <p>hogethree</p>
        </TabPanel>
        <TabPanel>
          <p>hugaone</p>
          <p>hugatwo</p>
          <p>hugathree</p>
        </TabPanel>
        <TabPanel>
          <p>hegeone</p>
          <p>hegetwo</p>
          <p>hegethree</p>
        </TabPanel>
      </TabPanels>
      </Tabs>
      <Tabs  colorScheme="blue" variant="enclosed-colored" >
      <TabList>
        <Tab>hoge</Tab>
        <Tab>huga</Tab>
        <Tab>hege</Tab>
      </TabList>
      <TabPanels>
        <TabPanel>
          <p>hogeone</p>
          <p>hogetwo</p>
          <p>hogethree</p>
        </TabPanel>
        <TabPanel>
          <p>hugaone</p>
          <p>hugatwo</p>
          <p>hugathree</p>
        </TabPanel>
        <TabPanel>
          <p>hegeone</p>
          <p>hegetwo</p>
          <p>hegethree</p>
        </TabPanel>
      </TabPanels>
      </Tabs>
      <Tabs  colorScheme="yellow" variant="soft-rounded" >
      <TabList>
        <Tab>hoge</Tab>
        <Tab>huga</Tab>
        <Tab>hege</Tab>
      </TabList>
      <TabPanels>
        <TabPanel>
          <p>hogeone</p>
          <p>hogetwo</p>
          <p>hogethree</p>
        </TabPanel>
        <TabPanel>
          <p>hugaone</p>
          <p>hugatwo</p>
          <p>hugathree</p>
        </TabPanel>
        <TabPanel>
          <p>hegeone</p>
          <p>hegetwo</p>
          <p>hegethree</p>
        </TabPanel>
      </TabPanels>
      </Tabs>
      <Tabs  colorScheme="pink" variant="solid-rounded" >
      <TabList>
        <Tab>hoge</Tab>
        <Tab>huga</Tab>
        <Tab>hege</Tab>
      </TabList>
      <TabPanels>
        <TabPanel>
          <p>hogeone</p>
          <p>hogetwo</p>
          <p>hogethree</p>
        </TabPanel>
        <TabPanel>
          <p>hugaone</p>
          <p>hugatwo</p>
          <p>hugathree</p>
        </TabPanel>
        <TabPanel>
          <p>hegeone</p>
          <p>hegetwo</p>
          <p>hegethree</p>
        </TabPanel>
      </TabPanels>
      </Tabs>
    </>
  )
}